-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 12:10:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CupidCo DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CupidCo DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CupidCo DB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `CupidCo DB` ;

-- -----------------------------------------------------
-- Table `CupidCo DB`.`Customer_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CupidCo DB`.`Customer_Details` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Dath_Of_Birth` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Email_Address` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Profile_Picture` BLOB NOT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CupidCo DB`.`User_Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CupidCo DB`.`User_Login` (
  `Login_ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Customer_ID` INT NOT NULL,
  PRIMARY KEY (`Login_ID`, `Customer_ID`),
  INDEX `fk_User_Login_Customer_Details_idx` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Login_Customer_Details`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `CupidCo DB`.`Customer_Details` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CupidCo DB`.`Customer_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CupidCo DB`.`Customer_Details` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Dath_Of_Birth` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Email_Address` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Profile_Picture` BLOB NOT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;

USE `shopdb` ;

-- -----------------------------------------------------
-- Table `shopdb`.`barcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`barcode` (
  `barcode_id` INT NOT NULL,
  `barcode_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`barcode_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`customer_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`customer_category` (
  `customer_category_id` INT NOT NULL AUTO_INCREMENT,
  `customer_type` VARCHAR(45) NOT NULL,
  `customer_category_description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`customer` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(100) NOT NULL,
  `customer_address` VARCHAR(100) NULL DEFAULT NULL,
  `customer_phone` VARCHAR(45) NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `category_id`),
  INDEX `fk_customer_customer_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_customer_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shopdb`.`customer_category` (`customer_category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`payment_method` (
  `payment_method_id` INT NOT NULL,
  `payment_method_type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `curruncyType` VARCHAR(45) NOT NULL,
  `bankName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`payment_method_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`cash_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`cash_payment` (
  `cash_invoice_id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `payment_method_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `invoice_category_id` INT NOT NULL,
  PRIMARY KEY (`cash_invoice_id`, `customer_id`, `invoice_category_id`),
  INDEX `payment_method_id_idx` (`payment_method_id` ASC) VISIBLE,
  INDEX `fk_Cash_Payment_Customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_Cash_Payment_Invoice_Catergory1_idx` (`invoice_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cash_Payment_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shopdb`.`customer` (`customer_id`),
  CONSTRAINT `payment_method_id`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `shopdb`.`payment_method` (`payment_method_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`debt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`debt` (
  `debt_id` INT NOT NULL,
  `total_amount` VARCHAR(45) NOT NULL,
  `outstanding_amount` VARCHAR(25) NOT NULL,
  `last_pay_amount` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `next_date` DATE NOT NULL,
  `last_pay_date` DATE NOT NULL,
  `payment_method` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`debt_id`, `customer_id`),
  INDEX `payment_method_idx` (`payment_method` ASC) VISIBLE,
  INDEX `fk_Debt_Customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Debt_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shopdb`.`customer` (`customer_id`),
  CONSTRAINT `payment_method`
    FOREIGN KEY (`payment_method`)
    REFERENCES `shopdb`.`payment_method` (`payment_method_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`debt_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`debt_invoice` (
  `invoice_id` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `product_id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `debt_id` INT NOT NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `customer_name_idx` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`discont`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`discont` (
  `discount_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `discount_presentage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`expense_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`expense_category` (
  `expenses_category_id` INT NOT NULL,
  `category_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`expenses_category_id`),
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`user_role` (
  `role_id` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  `role_description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `profile_pic` MEDIUMBLOB NULL DEFAULT NULL,
  `user_role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `user_role_idx` (`user_role_id` ASC) VISIBLE,
  CONSTRAINT `user_role`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `shopdb`.`user_role` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`expenses` (
  `expense_id` INT NOT NULL AUTO_INCREMENT,
  `expenses_date` VARCHAR(45) NOT NULL,
  `expenses_category_id` INT NOT NULL,
  `expenses_description` VARCHAR(255) NOT NULL,
  `expenses_amount` VARCHAR(45) NOT NULL,
  `payment_method` INT NOT NULL,
  `vendor_supplier` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`expense_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `expenses_category_id_idx` (`expenses_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_expenses_category`
    FOREIGN KEY (`expenses_category_id`)
    REFERENCES `shopdb`.`expense_category` (`expenses_category_id`),
  CONSTRAINT `fk_expenses_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `shopdb`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1107
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`invoice_catergory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`invoice_catergory` (
  `invoice_category_id` INT NOT NULL,
  `invoice_category_type` VARCHAR(45) NOT NULL,
  `invoice_category_description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`invoice_category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`product_category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`product_type` (
  `product_type_id` INT NOT NULL,
  `product_type` VARCHAR(45) NOT NULL,
  `product_type_description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`product_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`store_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`store_location` (
  `store_location_id` INT NOT NULL,
  `store_location_name` VARCHAR(50) NOT NULL,
  `store_location_description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`store_location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`supplier` (
  `supplier_id` INT NOT NULL,
  `supplier_name` VARCHAR(45) NOT NULL,
  `supplier_contact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `reciving_price` VARCHAR(45) NOT NULL,
  `selling_price` VARCHAR(45) NOT NULL,
  `stock_quantity` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  `dimensions` VARCHAR(45) NULL DEFAULT NULL,
  `manufacturing_date` VARCHAR(45) NULL DEFAULT NULL,
  `expiry_date` VARCHAR(45) NULL DEFAULT NULL,
  `supplier_id` INT NOT NULL,
  `barcode_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  `store_location_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `barcode_id_idx` (`barcode_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  INDEX `product_categoey_id_idx` (`product_type_id` ASC) VISIBLE,
  INDEX `discount_id_idx` (`discount_id` ASC) VISIBLE,
  INDEX `store_location_id_idx` (`store_location_id` ASC) VISIBLE,
  CONSTRAINT `barcode_id`
    FOREIGN KEY (`barcode_id`)
    REFERENCES `shopdb`.`barcode` (`barcode_id`),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `shopdb`.`product_category` (`category_id`),
  CONSTRAINT `discount_id`
    FOREIGN KEY (`discount_id`)
    REFERENCES `shopdb`.`discont` (`discount_id`),
  CONSTRAINT `product_categoey_id`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `shopdb`.`product_type` (`product_type_id`),
  CONSTRAINT `store_location_id`
    FOREIGN KEY (`store_location_id`)
    REFERENCES `shopdb`.`store_location` (`store_location_id`),
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `shopdb`.`supplier` (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`receipt` (
  `receipt_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` DATETIME NOT NULL,
  `pay_amount` VARCHAR(45) NOT NULL,
  `debt_invoice_id` INT NOT NULL,
  PRIMARY KEY (`receipt_id`),
  INDEX `Debt_id_idx` (`debt_invoice_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`return_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`return_invoice` (
  `return_id` INT NOT NULL AUTO_INCREMENT,
  `return_time` VARCHAR(45) NOT NULL,
  `return_date` VARCHAR(45) NOT NULL,
  `return_amount` VARCHAR(45) NOT NULL,
  `pre_amount` VARCHAR(45) NULL DEFAULT NULL,
  `currunt_amount` VARCHAR(45) NULL DEFAULT NULL,
  `return_balance` VARCHAR(45) NULL DEFAULT NULL,
  `invoice_id` INT NOT NULL,
  PRIMARY KEY (`return_id`),
  INDEX `invoice_id_idx` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `invoice_id`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `shopdb`.`cash_payment` (`cash_invoice_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`sold_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`sold_items` (
  `sold_item_id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `profit` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`sold_item_id`, `product_id`, `user_id`, `customer_id`),
  INDEX `fk_sold_items_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_sold_items_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_sold_items_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_sold_items_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shopdb`.`customer` (`customer_id`),
  CONSTRAINT `fk_sold_items_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopdb`.`product` (`product_id`),
  CONSTRAINT `fk_sold_items_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shopdb`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11581
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`status` (
  `status_id` INT NOT NULL,
  `status_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `shopdb`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`user_profile` (
  `user_profile_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `sale` VARCHAR(45) NOT NULL,
  `profit` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_profile_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shopdb`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
