/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.zx.shopmanagementsystem.notifications;

import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;
import com.zx.shopmanagementsystem.ui.NewInvoice;
import java.awt.Color;
import javax.swing.JFrame;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author User
 */
public class Payment extends javax.swing.JDialog {

    /**
     * Creates new form ConfirmDialog
     */
    private final JFrame fram;
    private MessageType messageType = MessageType.CANCEL;
    
    Func func = new Func();
    IconLocation il = new IconLocation();
    
    public Payment(JFrame fram) {
        super(fram, true);
        this.fram = fram;
        initComponents();
        setBackground(new Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.raven.swing.PanelBorder();
        priceLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paymentTxt = new com.zx.shopmanagementsystem.components.RoundedText();
        jLabel4 = new javax.swing.JLabel();
        yesLbl = new javax.swing.JLabel();
        noLbl = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        priceLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        priceLbl.setForeground(new java.awt.Color(153, 0, 153));
        panelBorder1.add(priceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Total Price");
        panelBorder1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 110, 30));

        paymentTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        paymentTxt.setHintText("Enter Price...");
        paymentTxt.setPreferredSize(new java.awt.Dimension(129, 50));
        panelBorder1.add(paymentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Payment");
        panelBorder1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, 30));

        yesLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\PayNow.png")); // NOI18N
        yesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesLblMouseClicked(evt);
            }
        });
        panelBorder1.add(yesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 130, 30));

        noLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\NoIcon.png")); // NOI18N
        noLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noLblMouseClicked(evt);
            }
        });
        panelBorder1.add(noLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 215, 120, 40));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\PayScreen.png")); // NOI18N
        panelBorder1.add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yesLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesLblMouseClicked
        // TODO add your handling code here:
        messageType = MessageType.YES;
        Payment.this.dispose();
    }//GEN-LAST:event_yesLblMouseClicked
    
    private void noLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noLblMouseClicked
        // TODO add your handling code here:
        messageType = MessageType.CANCEL;
        Payment.this.dispose();
    }//GEN-LAST:event_noLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public Payment.MessageType getMessageType() {
        return messageType;
    }
    
    public static enum MessageType {
        CANCEL, YES
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel noLbl;
    private com.raven.swing.PanelBorder panelBorder1;
    private com.zx.shopmanagementsystem.components.RoundedText paymentTxt;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JLabel yesLbl;
    // End of variables declaration//GEN-END:variables

    public void showMessage(double totalPrice) {
        priceLbl.setText(String.valueOf(totalPrice));
        setVisible(true);
        
    }
    
    public String getPaymentValue() {
        return paymentTxt.getText();
    }
    
}
