/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.zx.shopmanagementsystem.notifications;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class PrintType extends javax.swing.JDialog {

    /**
     * Creates new form ConfirmDialog
     */
    private final JFrame fram;
    private MessageType messageType = MessageType.CANCEL;
    int reportType = 0;

    public PrintType(JFrame fram) {
        super(fram, true);
        this.fram = fram;
        initComponents();
        setBackground(new Color(255, 255, 255, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noBtnLbl = new javax.swing.JLabel();
        yesBtnLbl = new javax.swing.JLabel();
        typeCombo = new com.zx.shopmanagementsystem.components.ComboBoxSuggestion();
        iconLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noBtnLbl.setPreferredSize(new java.awt.Dimension(50, 50));
        noBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noBtnLblMouseClicked(evt);
            }
        });
        getContentPane().add(noBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 150, 40));

        yesBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yesBtnLbl.setPreferredSize(new java.awt.Dimension(50, 50));
        yesBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesBtnLblMouseClicked(evt);
            }
        });
        getContentPane().add(yesBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, 40));

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Excel", "PDF" }));
        typeCombo.setFont(new java.awt.Font("Poppins SemiBold", 1, 13)); // NOI18N
        getContentPane().add(typeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 45));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\ReportType.png")); // NOI18N
        getContentPane().add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 526, 296));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public MessageType getMessageType() {
        return messageType;
    }

    public int getReportType() {
        return reportType;
    }
    private void yesBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesBtnLblMouseClicked
        // TODO add your handling code here:
        messageType = MessageType.YES;
        if (typeCombo.getSelectedIndex() == 0) {
            reportType = 0;
        } else {
            reportType = 1;
        }
        PrintType.this.dispose();

    }//GEN-LAST:event_yesBtnLblMouseClicked

    private void noBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noBtnLblMouseClicked
        // TODO add your handling code here:
        messageType = MessageType.CANCEL;
        PrintType.this.dispose();
    }//GEN-LAST:event_noBtnLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static enum MessageType {
        CANCEL, YES
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLbl;
    private javax.swing.JLabel noBtnLbl;
    private com.zx.shopmanagementsystem.components.ComboBoxSuggestion typeCombo;
    private javax.swing.JLabel yesBtnLbl;
    // End of variables declaration//GEN-END:variables

    public void showMessage() {
        //titleLbl.setText(title);
        //messageLbl.setText(message);
        setLocationRelativeTo(fram);
        setVisible(true);
    }
}
