/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.zx.shopmanagementsystem.assests;

/**
 *
 * @author User
 */
public class IconLocation {

    public String searchIconAnimated = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Search_Animation.gif";
    public String searchIconNormal = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Search_Icon.png";
    public String showPassword = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/ShowPassword.png";
    public String hidePassword = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/HidePassword.png";
    public String closeRedIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Close_Red.png";
    public String closeBlackIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Close_Black.png";
    public String minimiseBlackIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Minimise_Black.png";
    public String minimiseGreenIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Minimise_Green.png";
    public String LoginPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/LoginPurpleIcon.png";
    public String LoginWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/LoginWhiteIcon.png";
    public String updateAnimatedIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/update_Animated.gif";
    public String updateWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/UpdateWhiteIcon.png";
    public String UpdatePurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/UpdatePurpleIcon.png";
    public String doneIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/doneIcon.png";
    public String warningIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/warningIcon.png";
    public String errorIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/errorIcon.png";
    public String okWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/okWhite.png";
    public String okPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/okPurple.png";
    public String uploadPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Upload_Purple.png";
    public String uploadWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/Upload_White.png";
    public String profileIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/UserIcon.png";
    public String RegisterPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/RegisterPurpleIcon.png";
    public String RegisterWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/RegisterWhiteIcon.png";
    public String analysisPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AnalysisPurple.png";
    public String analysisWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AnalysisWhite.png";
    public String customerManagementPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/CustomerManagementPurple.png";
    public String customerManagementWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/CustomerManagementWhite.png";
    public String dashboardPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DashboardPurple.png";
    public String dashboardWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DashboardWhite.png";
    public String debtManagemetPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DebtManagementPurple.png";
    public String debtManagemetWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DebtManagementWhite.png";
    public String helpPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/HelpPurple.png";
    public String helpWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/HelpWhite.png";
    public String inventoryManagementPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/InventoryManagementPurple.png";
    public String inventoryManagementWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/InventoryManagementWhite.png";
    public String invoiceCreationPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/InvoiceCreationPurple.png";
    public String invoiceCreationWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/InvoiceCreationWhite.png";
    public String logoutPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/LogoutPurple.png";
    public String logoutWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/LogoutWhite.png";
    public String productManagementPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/ProductManagementPurple.png";
    public String productManagementWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/ProductManagementWhite.png";
    public String reportGenerationPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/ReportGenerationPurple.png";
    public String reportGenerationWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/ReportGenerationWhite.png";
    public String supplierManagementPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SupplierManagementPurple.png";
    public String supplierManagementWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SupplierManagementWhite.png";
    public String userManagementPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/UserManagementPurple.png";
    public String userManagementWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/UserManagementWhite.png";
    public String addBarcodePurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddBarcodePurple.png";
    public String addBarcodeWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddBarcodeWhite.png";
    public String addDiscountPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddDiscountPurple.png";
    public String addDiscountWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddDiscountWhite.png";
    public String addProductCategoryPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductCategaryPurple.png";
    public String addProductCategoryWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductCategaryWhite.png";
    public String addProductPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductPurple.png";
    public String addProductWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductWhite.png";
    public String addProductTypePurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductTypePurple.png";
    public String addProductTypeWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductTypeWhite.png";
    public String addStoreLocationPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddStoreLocationPurple.png";
    public String addStoreLocationWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddStoreLocationWhite.png";
    public String addCustomerPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddCustomerPurpleIcon.png";
    public String addCustomerWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddCustomerWhiteIcon.png";
    public String addCustomerCategoryPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddCustomerCategoryPurpleIcon.png";
    public String addCustomerCategoryWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddCustomerCategoryWhiteIcon.png";
    public String addSupplierPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddSupplierPurpleIcon.png";
    public String addSupplierWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddSupplierWhiteIcon.png";
    public String addUserPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddUserPurpleIcon.png";
    public String addUserWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddUserWhiteIcon.png";
    public String refreshPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/RefreshPurpleIcon.png";
    public String refreshWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/RefreshWhiteIcon.png";
    public String deleteWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DeleteWhiteIcon.png";
    public String deleteRedIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DeleteRedIcon.png";
    public String editImageIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/EditImageIcon.png";
    public String editUserDetailsPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/EditUserDetailsPurpleIcon.png";
    public String editUserDetailsWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/EditUserDetailsWhiteIcon.png";
    public String userDetailsScreen = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/images/User_Details.png";
    public String customerDetails = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/images/CustomerDetails.png";
    public String updateCustomerDetails = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/images/UpdateCustomerDetails.png";
    public String editUserScreen = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/images/UpdateUserDetails.png";
    public String supplierDetails = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/images/SupplierDetails.png";
    public String editSupplierDetils = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/images/EditSupplierDetils.png";
    public String noIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/NoIcon.png";
    public String yesIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/YesIcon.png";
    public String submitPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SubmitPurpleIcon.png";
    public String submitWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SubmitWhiteIcon.png";
    public String deleteCustomerRedIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DeleteCustomerRedIcon.png";
    public String deleteCustomerWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/DeleteCustomerWhiteIcon.png";
    public String editDetailsPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/EditPurpleIcon.png";
    public String editDetailsWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/EditWhiteIcon.png";
    public String zxlogo = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/zxlogo.png";
    public String logo = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/logo.png";
    public String addPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddPurpleIcon.png";
    public String addWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddWhiteIcon.png";
    public String searchBardcodeIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SearchBardcodeIcon.png";
    public String calenderIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/CalenderIcon.png";
    public String addProductPurpleIcon2 = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductPurpleIcon.png";
    public String addProductWhiteIcon2 = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddProductWhiteIcon.png";
    public String AddInvoice1Icon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/addInvoiceIcon.png";
    public String AddInvoice2Icon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddInvoice2.png";
    public String ClearDetails1Icon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/clearIcon.png";
    public String ClearDetails2Icon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/ClearDetails2.png";
    public String Payment1CheckOutIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/paymentIcon.png";
    public String Payment2CheckOutIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/PaymentCheckout2.png";
    public String PayNow = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/PayNow.png";
    public String PayNowShadow = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/PayNowShadow.png";
    public String CreateInvoicePurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/CreateInvoicePurpleIcon.png";
    public String CreateInvoiceWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/CreateInvoiceWhiteIcon.png";
    public String InvoiceCategoryPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/InvoiceCategoryPurpleIcon.png";
    public String InvoiceCategoryWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/InvoiceCategoryWhiteIcon.png";
    public String PaymentMethodPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/PaymentMethodPurpleIcon.png";
    public String PaymentMethodWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/PaymentMethodWhiteIcon.png";
    public String SavePurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SavePurpleIcon.png";
    public String SaveWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SaveWhiteIcon.png";
    public String SettingsMenuPurpleBtn = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SettingsMenuPurpleBtn.png";
    public String SettingsMenuWhiteBtn = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SettingsMenuWhiteBtn.png";
    public String AddNewDebtPurpleIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/AddNewDebtPurpleIcon.png";
    public String AddNewDebtWhiteIcon = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/SettingsMenuWhiteBtn.png";
    public String MinimizeIconBlue = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/MinimizeIconBlue.png";
    public String CloseBlue = "/C:/ShopManagementSystem/src/main/java/com/zx/shopmanagementsystem/icons/CloseBlue.png";
}
