/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zx.shopmanagementsystem.ui;

import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;
import com.zx.shopmanagementsystem.components.ScrollBarCustom;
import com.zx.shopmanagementsystem.dbconnection.JDBC;
import com.zx.shopmanagementsystem.notifications.ConfirmDialog;
import com.zx.shopmanagementsystem.notifications.MessageDialog;
import java.awt.Toolkit;
import java.sql.ResultSet;

/**
 *
 * @author User
 */
public class CustomerCategory extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCategory
     */
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(il.logo));
    }

    Func func = new Func();
    IconLocation il = new IconLocation();
    JDBC DB = new JDBC();

    boolean exsit;

    public CustomerCategory() {
        initComponents();

        setIconImage(Toolkit.getDefaultToolkit().getImage(il.logo));
        head1.setFrame(CustomerCategory.this);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeTxt = new com.zx.shopmanagementsystem.components.RoundedText();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxt = new javax.swing.JTextArea();
        submitBtnLbl = new javax.swing.JLabel();
        head1 = new com.zx.shopmanagementsystem.components.Head();
        iconLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        typeTxt.setHintText("Enter Customer Category Type");
        getContentPane().add(typeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 440, 50));

        panelBorder1.setBackground(new java.awt.Color(238, 238, 238));

        descriptionTxt.setColumns(20);
        descriptionTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionTxt.setRows(5);
        jScrollPane1.setViewportView(descriptionTxt);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 430, 160));

        submitBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitBtnLblMouseExited(evt);
            }
        });
        getContentPane().add(submitBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 200, 50));

        head1.setHeaderTextColor("#FFFFFF");
        head1.setHeaderTitle("");
        head1.setOpaque(false);
        getContentPane().add(head1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\CustomerCategory.png")); // NOI18N
        getContentPane().add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_submitBtnLblMouseEntered

    private void submitBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_submitBtnLblMouseExited

    private void submitBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnLblMouseClicked
        // TODO add your handling code here:
        addCategory();
    }//GEN-LAST:event_submitBtnLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionTxt;
    private com.zx.shopmanagementsystem.components.Head head1;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JLabel submitBtnLbl;
    private com.zx.shopmanagementsystem.components.RoundedText typeTxt;
    // End of variables declaration//GEN-END:variables

    private void categoryChecker(String type) {

        try {
            ResultSet rs = DB.getdata("SELECT * FROM customer_category WHERE customer_type = '" + type + "'");
            if (rs.next()) {
                System.out.println("Customer Type Exsist");
                exsit = true;
            } else {
                System.out.println("Customer Type Not Exsist");
                exsit = false;
            }
            rs.close();
            DB.con().close();
            rs.close();
        } catch (Exception ex) {
            System.out.println("Customer Category Category Checker : " + ex.getMessage());
        }
    }

    private void addCategory() {
        String type = typeTxt.getText();
        String description = descriptionTxt.getText();
        categoryChecker(type);
        MessageDialog DialogBox = new MessageDialog(this);

        //System.out.println(exsit);
        if (type.equals("")) {
            System.out.println("Customer Category Type Empty");
            DialogBox.showMessage("WARNING !!!", "Customer Category Type Empty", 2);
        } else if (description.equals("")) {
            System.out.println("Customer Description Empty");
            DialogBox.showMessage("WARNING !!!", "Customer Description Empty", 2);
        } else if (exsit) {
            DialogBox.showMessage("ERROR !!!", "Categoey Already Exsist", 3);
        } else {
            ConfirmDialog confrim = new ConfirmDialog(this);
            confrim.showMessage("Save", "Do you want to Add ?");
            if (confrim.getMessageType() == ConfirmDialog.MessageType.YES) {
                System.out.println("Yes");
                try {
                    DB.putdata("INSERT INTO customer_category (customer_type, customer_category_description) VALUES ('" + type + "','" + description + "');");
                    DialogBox.showMessage("Done !!!", "Category Saved!", 1);
                    clear();
                    DB.con().close();
                } catch (Exception ex) {
                    System.out.println("Add Category : " + ex.getMessage());
                }
            } else {
                System.out.println("No");
            }

        }
    }

    private void clear() {
        typeTxt.setText("");
        descriptionTxt.setText("");
    }
}
