/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zx.shopmanagementsystem.ui;

import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;
import com.zx.shopmanagementsystem.dbconnection.JDBC;
import com.zx.shopmanagementsystem.forms.SupplierManagement;
import com.zx.shopmanagementsystem.notifications.ConfirmDialog;
import com.zx.shopmanagementsystem.notifications.MessageDialog;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;

/**
 *
 * @author User
 */
public class SupplierDetails extends javax.swing.JFrame {

    /**
     * Creates new form SupplierDetails
     */
    Func func = new Func();
    IconLocation il = new IconLocation();
    JDBC DB = new JDBC();

    int supID;
    private SupplierManagement supplierManagement;

    public SupplierDetails(SupplierManagement supplierManagement) {
        this.supplierManagement = supplierManagement;
        initComponents();
        disableForm();
        setIconImage(Toolkit.getDefaultToolkit().getImage(il.logo));
        head1.setFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierNameTxt = new com.zx.shopmanagementsystem.components.RoundedText();
        supplierNumberTxt = new com.zx.shopmanagementsystem.components.RoundedText();
        editSupplierBtnLbl = new javax.swing.JLabel();
        deleteSupplierBtnLbl = new javax.swing.JLabel();
        updateSupplierBtnLbl = new javax.swing.JLabel();
        head1 = new com.zx.shopmanagementsystem.components.Head();
        IconLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierNameTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        supplierNameTxt.setHintText("Enter Customer Name");
        supplierNameTxt.setPreferredSize(new java.awt.Dimension(129, 40));
        getContentPane().add(supplierNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 260, 310, 50));

        supplierNumberTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        supplierNumberTxt.setHintText("Enter Customer Number");
        supplierNumberTxt.setPreferredSize(new java.awt.Dimension(129, 40));
        getContentPane().add(supplierNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 310, 50));

        editSupplierBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\EditDetailsPurpleIcon.png")); // NOI18N
        editSupplierBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editSupplierBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editSupplierBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editSupplierBtnLblMouseExited(evt);
            }
        });
        getContentPane().add(editSupplierBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        deleteSupplierBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\DeleteCustomerRedIcon.png")); // NOI18N
        deleteSupplierBtnLbl.setPreferredSize(new java.awt.Dimension(183, 54));
        deleteSupplierBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteSupplierBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteSupplierBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteSupplierBtnLblMouseExited(evt);
            }
        });
        getContentPane().add(deleteSupplierBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 470, 210, -1));

        updateSupplierBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\Update_Lable.png")); // NOI18N
        updateSupplierBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateSupplierBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateSupplierBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateSupplierBtnLblMouseExited(evt);
            }
        });
        getContentPane().add(updateSupplierBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, -1, -1));

        head1.setHeaderTextColor("#ffffff");
        head1.setHeaderTitle("Supplier Details");
        head1.setOpaque(false);
        getContentPane().add(head1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        IconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\SupplierDetails.png")); // NOI18N
        getContentPane().add(IconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSupplierBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSupplierBtnLblMouseClicked
        // TODO add your handling code here:
        enebleForm();
    }//GEN-LAST:event_editSupplierBtnLblMouseClicked

    private void editSupplierBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSupplierBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(editSupplierBtnLbl, il.editDetailsWhiteIcon);
    }//GEN-LAST:event_editSupplierBtnLblMouseEntered

    private void editSupplierBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSupplierBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(editSupplierBtnLbl, il.editDetailsPurpleIcon);
    }//GEN-LAST:event_editSupplierBtnLblMouseExited

    private void updateSupplierBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSupplierBtnLblMouseClicked
        // TODO add your handling code here:
        updateSupplier();
        supplierManagement.setTable();
    }//GEN-LAST:event_updateSupplierBtnLblMouseClicked

    private void updateSupplierBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSupplierBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(updateSupplierBtnLbl, il.updateWhiteIcon);
    }//GEN-LAST:event_updateSupplierBtnLblMouseEntered

    private void updateSupplierBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSupplierBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(updateSupplierBtnLbl, il.updateNormalIcon);
    }//GEN-LAST:event_updateSupplierBtnLblMouseExited

    private void deleteSupplierBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSupplierBtnLblMouseClicked
        // TODO add your handling code here:
        MessageDialog DialogBox = new MessageDialog(this);
        ConfirmDialog confrim = new ConfirmDialog(this);
        confrim.showMessage("Delete", "Do you want to Delete ?");
        if (confrim.getMessageType() == ConfirmDialog.MessageType.YES) {
            System.out.println("Yes");
            try {

                DB.putdata("DELETE FROM supplier WHERE supplier_id = '" + supID + "';");
                System.out.println("Data Deleted");
                DialogBox.showMessage("Deleted", "Supplier Deleted", 1);
                supplierManagement.setTable();
                this.dispose();

            } catch (Exception ex) {
                System.out.println("Delete Button Mouse Clicked (Supplier Details) : " + ex.getMessage());
            }
        } else {
            System.out.println("No");
        }
    }//GEN-LAST:event_deleteSupplierBtnLblMouseClicked

    private void deleteSupplierBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSupplierBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(deleteSupplierBtnLbl, il.deleteCustomerWhiteIcon);
    }//GEN-LAST:event_deleteSupplierBtnLblMouseEntered

    private void deleteSupplierBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSupplierBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(deleteSupplierBtnLbl, il.deleteCustomerRedIcon);
    }//GEN-LAST:event_deleteSupplierBtnLblMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SupplierManagement supplierManagementInstance = new SupplierManagement(); // Create an instance of SupplierManagement
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SupplierDetails supplierDetails = new SupplierDetails(supplierManagementInstance);
                supplierDetails.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconLbl;
    private javax.swing.JLabel deleteSupplierBtnLbl;
    private javax.swing.JLabel editSupplierBtnLbl;
    private com.zx.shopmanagementsystem.components.Head head1;
    private com.zx.shopmanagementsystem.components.RoundedText supplierNameTxt;
    private com.zx.shopmanagementsystem.components.RoundedText supplierNumberTxt;
    private javax.swing.JLabel updateSupplierBtnLbl;
    // End of variables declaration//GEN-END:variables

    private void enebleForm() {
        editSupplierBtnLbl.setVisible(false);
        deleteSupplierBtnLbl.setVisible(false);
        updateSupplierBtnLbl.setVisible(true);
        supplierNameTxt.setEditable(true);
        supplierNumberTxt.setEditable(true);
    }

    private void disableForm() {
        editSupplierBtnLbl.setVisible(true);
        deleteSupplierBtnLbl.setVisible(true);
        updateSupplierBtnLbl.setVisible(false);
        supplierNameTxt.setEditable(false);
        supplierNumberTxt.setEditable(false);
    }

    public void dataLoad(int supId) {
        supID = supId;

        try {
            ResultSet rs = DB.getdata("SELECT * FROM supplier WHERE supplier_id = '" + supId + "'");
            while (rs.next()) {
                //int supllierId = rs.getInt("supplier_id");
                String supplierName = rs.getString("supplier_name");
                String supplierNumber = rs.getString("supplier_contact");

                supplierNameTxt.setText(supplierName);
                supplierNumberTxt.setText(supplierNumber);
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void updateSupplier() {
        MessageDialog DialogBox = new MessageDialog(this);
        String supplierName = supplierNameTxt.getText();
        String supplierNumber = supplierNumberTxt.getText();

        if (supplierName.equals("")) {
            System.out.println("Supplier Name Empty");
            DialogBox.showMessage("WARNING", "Supplier Name Empty", 2);
        } else if (supplierNumber.equals("")) {
            System.out.println("Supplier Number Empty");
            DialogBox.showMessage("WARNING", "Supplier Number Empty", 2);
        } else {
            if (func.isValidMobileNumber(supplierNumber)) {
                try {
                    //System.out.println("Valid Mobile Number");
                    DB.putdata("UPDATE supplier SET supplier_name = '" + supplierName + "', supplier_contact = '" + supplierNumber + "' WHERE supplier_id = '" + supID + "'");
                    System.out.println("Data Updated");
                    DialogBox.showMessage("Done", "Supplier Updated", 1);
                    disableForm();
                    SupplierManagement sm = new SupplierManagement();
                    sm.setTable();
                } catch (Exception ex) {
                    System.out.println("Supplier Details -> Update Function " + ex.getMessage());
                }
            } else {
                System.out.println("Not Valid Number");
                DialogBox.showMessage("ERROR!!!", "Supplier Number Not Valid Format", 3);
            }
        }
    }
}
