/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.zx.shopmanagementsystem.forms;

import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;
import com.zx.shopmanagementsystem.dbconnection.JDBC;
import com.zx.shopmanagementsystem.table.TableCustom;
import com.zx.shopmanagementsystem.ui.CustomerCategory;
import com.zx.shopmanagementsystem.ui.CustomerDetails;
import com.zx.shopmanagementsystem.ui.CustomerRegistration;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerManagement extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    Func func = new Func();
    IconLocation il = new IconLocation();
    JDBC DB = new JDBC();
    CustomerCategory cc = new CustomerCategory();

    public CustomerManagement() {
        initComponents();
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        tableDataClear();
        tableDataLoader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCustomerCategoryBtnLbl = new javax.swing.JLabel();
        addCustomerBtnLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTbl = new javax.swing.JTable();
        refreshBtnLbl = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1015, 738));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCustomerCategoryBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddCustomerCategoryPurpleIcon.png")); // NOI18N
        addCustomerCategoryBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerCategoryBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCustomerCategoryBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCustomerCategoryBtnLblMouseExited(evt);
            }
        });
        add(addCustomerCategoryBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 259, 36));

        addCustomerBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddCustomerPurpleIcon.png")); // NOI18N
        addCustomerBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCustomerBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCustomerBtnLblMouseExited(evt);
            }
        });
        add(addCustomerBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 175, 36));

        customerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "Address", "Phone Number", "Category"
            }
        ));
        customerTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 940, 480));

        refreshBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\RefreshPurpleIcon.png")); // NOI18N
        refreshBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshBtnLblMouseExited(evt);
            }
        });
        add(refreshBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, -1, -1));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\CustomerManagement.png")); // NOI18N
        iconLbl.setPreferredSize(new java.awt.Dimension(1015, 738));
        add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addCustomerBtnLbl, il.addCustomerWhiteIcon);
    }//GEN-LAST:event_addCustomerBtnLblMouseEntered

    private void addCustomerBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addCustomerBtnLbl, il.addCustomerPurpleIcon);
    }//GEN-LAST:event_addCustomerBtnLblMouseExited

    private void addCustomerCategoryBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerCategoryBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addCustomerCategoryBtnLbl, il.addCustomerCategoryWhiteIcon);
    }//GEN-LAST:event_addCustomerCategoryBtnLblMouseEntered

    private void addCustomerCategoryBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerCategoryBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addCustomerCategoryBtnLbl, il.addCustomerCategoryPurpleIcon);
    }//GEN-LAST:event_addCustomerCategoryBtnLblMouseExited

    private void addCustomerBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtnLblMouseClicked
        // TODO add your handling code here:
        CustomerRegistration cr = new CustomerRegistration();
        cr.setVisible(true);
    }//GEN-LAST:event_addCustomerBtnLblMouseClicked

    private void customerTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTblMouseClicked
        // TODO add your handling code here:
        int row = customerTbl.getSelectedRow();
        int userID = Integer.parseInt((String) customerTbl.getModel().getValueAt(row, 0));
        CustomerDetails cd = new CustomerDetails();
        cd.setVisible(true);
        cd.dataLoad(userID);
    }//GEN-LAST:event_customerTblMouseClicked

    private void refreshBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(refreshBtnLbl, il.refreshWhiteIcon);
    }//GEN-LAST:event_refreshBtnLblMouseEntered

    private void refreshBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(refreshBtnLbl, il.refreshPurpleIcon);
    }//GEN-LAST:event_refreshBtnLblMouseExited

    private void refreshBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnLblMouseClicked
        // TODO add your handling code here:
        panalRefresh();
    }//GEN-LAST:event_refreshBtnLblMouseClicked

    private void addCustomerCategoryBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerCategoryBtnLblMouseClicked
        // TODO add your handling code here:
        cc.setVisible(true);
    }//GEN-LAST:event_addCustomerCategoryBtnLblMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCustomerBtnLbl;
    private javax.swing.JLabel addCustomerCategoryBtnLbl;
    private javax.swing.JTable customerTbl;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel refreshBtnLbl;
    // End of variables declaration//GEN-END:variables

    private void tableDataLoader() {
        try {
            java.sql.ResultSet rs = DB.getdata("SELECT * FROM customer");
            while (rs.next()) {
                String customerId = String.valueOf(rs.getInt("customer_id"));
                String customerName = String.valueOf(rs.getString("customer_name"));
                String customerAddress = String.valueOf(rs.getString("customer_address"));
                String customerPhone = String.valueOf(rs.getString("customer_phone"));
                String customerCategoryId = String.valueOf(rs.getString("category_id"));

//                System.out.println("User ID" + userId);
//                System.out.println("User Name" + userName);
//                System.out.println("Full Name" + fullName);
                String table_data[] = {customerId, customerName, customerAddress, customerPhone, customerCategoryId};
                DefaultTableModel table = (DefaultTableModel) customerTbl.getModel();
                table.addRow(table_data);

            }
        } catch (Exception ex) {
            System.out.println("User Management Table Data Loader : " + ex);
        }
    }

    private void tableDataClear() {
        try {
            while (0 <= customerTbl.getRowCount()) {
                DefaultTableModel table = (DefaultTableModel) customerTbl.getModel();
                table.removeRow(customerTbl.getRowCount() - 1);
            }
        } catch (Exception e) {
            System.out.println("User Management Table Data Clear : " + e);
        }
    }

    public void panalRefresh() {
        tableDataClear();
        tableDataLoader();
        System.out.println("Function Run");
    }
}
