/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.zx.shopmanagementsystem.forms;

/**
 *
 * @author User
 */
public class Expenses extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Expenses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expensesBtnLbl = new javax.swing.JLabel();
        expensesCategotyBtnLbl = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1116, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(expensesBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 86, 200, 40));
        add(expensesCategotyBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 86, 270, 40));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\ExpensesDashboardScreen.png")); // NOI18N
        add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel expensesBtnLbl;
    private javax.swing.JLabel expensesCategotyBtnLbl;
    private javax.swing.JLabel iconLbl;
    // End of variables declaration//GEN-END:variables
}
