/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.zx.shopmanagementsystem.forms;

import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;
import com.zx.shopmanagementsystem.ui.AddBarcode;
import com.zx.shopmanagementsystem.ui.AddDiscount;
import com.zx.shopmanagementsystem.ui.AddProductCategory;
import com.zx.shopmanagementsystem.ui.AddProductType;
import com.zx.shopmanagementsystem.ui.AddStoreLocation;

/**
 *
 * @author User
 */
public class ProductManagement extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    Func func = new Func();
    IconLocation il = new IconLocation();
    
    public ProductManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProductTypeBtnLbl = new javax.swing.JLabel();
        addProductBtnLbl = new javax.swing.JLabel();
        addProductCategoryBtnLbl = new javax.swing.JLabel();
        addBarcodeBtnLbl = new javax.swing.JLabel();
        addDiscountBrnLbl = new javax.swing.JLabel();
        addStoreLocationBtnLbl = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1015, 738));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addProductTypeBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddProductTypePurple.png")); // NOI18N
        addProductTypeBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductTypeBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductTypeBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductTypeBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductTypeBtnLblMouseExited(evt);
            }
        });
        add(addProductTypeBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        addProductBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddProductPurple.png")); // NOI18N
        addProductBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductBtnLblMouseExited(evt);
            }
        });
        add(addProductBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        addProductCategoryBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddProductCategaryPurple.png")); // NOI18N
        addProductCategoryBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductCategoryBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductCategoryBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductCategoryBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductCategoryBtnLblMouseExited(evt);
            }
        });
        add(addProductCategoryBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        addBarcodeBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddBarcodePurple.png")); // NOI18N
        addBarcodeBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBarcodeBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBarcodeBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBarcodeBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBarcodeBtnLblMouseExited(evt);
            }
        });
        add(addBarcodeBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        addDiscountBrnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddDiscountPurple.png")); // NOI18N
        addDiscountBrnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addDiscountBrnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDiscountBrnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDiscountBrnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addDiscountBrnLblMouseExited(evt);
            }
        });
        add(addDiscountBrnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        addStoreLocationBtnLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddStoreLocationPurple.png")); // NOI18N
        addStoreLocationBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStoreLocationBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStoreLocationBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addStoreLocationBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addStoreLocationBtnLblMouseExited(evt);
            }
        });
        add(addStoreLocationBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\ProductManagement.png")); // NOI18N
        add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1015, 738));
    }// </editor-fold>//GEN-END:initComponents

    private void addProductBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addProductBtnLbl, il.addProductWhiteIcon);
    }//GEN-LAST:event_addProductBtnLblMouseEntered
    
    private void addProductBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addProductBtnLbl, il.addProductPurpleIcon);
    }//GEN-LAST:event_addProductBtnLblMouseExited
    
    private void addProductCategoryBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductCategoryBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addProductCategoryBtnLbl, il.addProductCategoryWhiteIcon);
    }//GEN-LAST:event_addProductCategoryBtnLblMouseEntered
    
    private void addProductCategoryBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductCategoryBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addProductCategoryBtnLbl, il.addProductCategoryPurpleIcon);
    }//GEN-LAST:event_addProductCategoryBtnLblMouseExited
    
    private void addProductTypeBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductTypeBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addProductTypeBtnLbl, il.addProductTypeWhiteIcon);
    }//GEN-LAST:event_addProductTypeBtnLblMouseEntered
    
    private void addProductTypeBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductTypeBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addProductTypeBtnLbl, il.addProductTypePurpleIcon);
    }//GEN-LAST:event_addProductTypeBtnLblMouseExited
    
    private void addDiscountBrnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDiscountBrnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addDiscountBrnLbl, il.addDiscountWhiteIcon);
    }//GEN-LAST:event_addDiscountBrnLblMouseEntered
    
    private void addDiscountBrnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDiscountBrnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addDiscountBrnLbl, il.addDiscountPurpleIcon);
    }//GEN-LAST:event_addDiscountBrnLblMouseExited
    
    private void addBarcodeBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBarcodeBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addBarcodeBtnLbl, il.addBarcodeWhiteIcon);
    }//GEN-LAST:event_addBarcodeBtnLblMouseEntered
    
    private void addBarcodeBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBarcodeBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addBarcodeBtnLbl, il.addBarcodePurpleIcon);
    }//GEN-LAST:event_addBarcodeBtnLblMouseExited
    
    private void addStoreLocationBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStoreLocationBtnLblMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addStoreLocationBtnLbl, il.addStoreLocationWhiteIcon);
    }//GEN-LAST:event_addStoreLocationBtnLblMouseEntered
    
    private void addStoreLocationBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStoreLocationBtnLblMouseExited
        // TODO add your handling code here:
        func.iconSetter(addStoreLocationBtnLbl, il.addStoreLocationPurpleIcon);
    }//GEN-LAST:event_addStoreLocationBtnLblMouseExited
    
    private void addBarcodeBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBarcodeBtnLblMouseClicked
        // TODO add your handling code here:
        AddBarcode addbarcode = new AddBarcode();
        addbarcode.setVisible(true);
    }//GEN-LAST:event_addBarcodeBtnLblMouseClicked
    
    private void addDiscountBrnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDiscountBrnLblMouseClicked
        // TODO add your handling code here:
        AddDiscount ad = new AddDiscount();
        ad.setVisible(true);
    }//GEN-LAST:event_addDiscountBrnLblMouseClicked
    
    private void addProductCategoryBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductCategoryBtnLblMouseClicked
        // TODO add your handling code here:
        AddProductCategory apc = new AddProductCategory();
        apc.setVisible(true);
    }//GEN-LAST:event_addProductCategoryBtnLblMouseClicked
    
    private void addProductTypeBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductTypeBtnLblMouseClicked
        // TODO add your handling code here:
        AddProductType apt = new AddProductType();
        apt.setVisible(true);
    }//GEN-LAST:event_addProductTypeBtnLblMouseClicked
    
    private void addStoreLocationBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStoreLocationBtnLblMouseClicked
        // TODO add your handling code here:
        AddStoreLocation asl = new AddStoreLocation();
        asl.setVisible(true);
    }//GEN-LAST:event_addStoreLocationBtnLblMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBarcodeBtnLbl;
    private javax.swing.JLabel addDiscountBrnLbl;
    private javax.swing.JLabel addProductBtnLbl;
    private javax.swing.JLabel addProductCategoryBtnLbl;
    private javax.swing.JLabel addProductTypeBtnLbl;
    private javax.swing.JLabel addStoreLocationBtnLbl;
    private javax.swing.JLabel iconLbl;
    // End of variables declaration//GEN-END:variables
}
