/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.zx.shopmanagementsystem.forms;

import com.zx.shopmanagementsystem.assests.DisplayFileExample;
import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;
import com.zx.shopmanagementsystem.table.TableCustom;
import com.zx.shopmanagementsystem.ui.AddBarcode;
import com.zx.shopmanagementsystem.ui.AddDiscount;
import com.zx.shopmanagementsystem.ui.AddProduct;
import com.zx.shopmanagementsystem.ui.AddProductCategory;
import com.zx.shopmanagementsystem.ui.AddProductType;
import com.zx.shopmanagementsystem.ui.AddStoreLocation;
import com.zx.shopmanagementsystem.ui.ReturnItems;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author User
 */
public class ProductManagement extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    Func func = new Func();
    IconLocation il = new IconLocation();

    public ProductManagement() {
        initComponents();
        tableDataClear();
        tableDataLoader();
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        qrTbl.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
        jScrollPane1.setViewportView(qrTbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProductTypeBtnLbl = new javax.swing.JLabel();
        addProductBtnLbl = new javax.swing.JLabel();
        addProductCategoryBtnLbl = new javax.swing.JLabel();
        addBarcodeBtnLbl = new javax.swing.JLabel();
        addDiscountBrnLbl = new javax.swing.JLabel();
        addStoreLocationBtnLbl = new javax.swing.JLabel();
        returnItemsBtnLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qrTbl = new javax.swing.JTable();
        iconLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1116, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addProductTypeBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductTypeBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductTypeBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductTypeBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductTypeBtnLblMouseExited(evt);
            }
        });
        add(addProductTypeBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 150, 50));

        addProductBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductBtnLblMouseExited(evt);
            }
        });
        add(addProductBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 95, 150, 55));

        addProductCategoryBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductCategoryBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductCategoryBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductCategoryBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductCategoryBtnLblMouseExited(evt);
            }
        });
        add(addProductCategoryBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 140, 50));

        addBarcodeBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBarcodeBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBarcodeBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBarcodeBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBarcodeBtnLblMouseExited(evt);
            }
        });
        add(addBarcodeBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 150, 50));

        addDiscountBrnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addDiscountBrnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDiscountBrnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDiscountBrnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addDiscountBrnLblMouseExited(evt);
            }
        });
        add(addDiscountBrnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, 50));

        addStoreLocationBtnLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStoreLocationBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStoreLocationBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addStoreLocationBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addStoreLocationBtnLblMouseExited(evt);
            }
        });
        add(addStoreLocationBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 150, 50));

        returnItemsBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnItemsBtnLblMouseClicked(evt);
            }
        });
        add(returnItemsBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 155, 60));

        qrTbl.setFont(new java.awt.Font("Poppins ExtraBold", 1, 13)); // NOI18N
        qrTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(qrTbl);
        if (qrTbl.getColumnModel().getColumnCount() > 0) {
            qrTbl.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 260, 1065, 432));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\ProductManagement.png")); // NOI18N
        add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1116, 718));
    }// </editor-fold>//GEN-END:initComponents

    private void addProductBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addProductBtnLblMouseEntered

    private void addProductBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addProductBtnLblMouseExited

    private void addProductCategoryBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductCategoryBtnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addProductCategoryBtnLblMouseEntered

    private void addProductCategoryBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductCategoryBtnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addProductCategoryBtnLblMouseExited

    private void addProductTypeBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductTypeBtnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addProductTypeBtnLblMouseEntered

    private void addProductTypeBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductTypeBtnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addProductTypeBtnLblMouseExited

    private void addDiscountBrnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDiscountBrnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addDiscountBrnLblMouseEntered

    private void addDiscountBrnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDiscountBrnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addDiscountBrnLblMouseExited

    private void addBarcodeBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBarcodeBtnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addBarcodeBtnLblMouseEntered

    private void addBarcodeBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBarcodeBtnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addBarcodeBtnLblMouseExited

    private void addStoreLocationBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStoreLocationBtnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addStoreLocationBtnLblMouseEntered

    private void addStoreLocationBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStoreLocationBtnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addStoreLocationBtnLblMouseExited

    private void addBarcodeBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBarcodeBtnLblMouseClicked
        // TODO add your handling code here:
        AddBarcode addbarcode = new AddBarcode();
        addbarcode.setVisible(true);
    }//GEN-LAST:event_addBarcodeBtnLblMouseClicked

    private void addDiscountBrnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDiscountBrnLblMouseClicked
        // TODO add your handling code here:
        AddDiscount ad = new AddDiscount();
        ad.setVisible(true);
    }//GEN-LAST:event_addDiscountBrnLblMouseClicked

    private void addProductCategoryBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductCategoryBtnLblMouseClicked
        // TODO add your handling code here:
        AddProductCategory apc = new AddProductCategory();
        apc.setVisible(true);
    }//GEN-LAST:event_addProductCategoryBtnLblMouseClicked

    private void addProductTypeBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductTypeBtnLblMouseClicked
        // TODO add your handling code here:
        AddProductType apt = new AddProductType();
        apt.setVisible(true);
    }//GEN-LAST:event_addProductTypeBtnLblMouseClicked

    private void addStoreLocationBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStoreLocationBtnLblMouseClicked
        // TODO add your handling code here:
        AddStoreLocation asl = new AddStoreLocation();
        asl.setVisible(true);
    }//GEN-LAST:event_addStoreLocationBtnLblMouseClicked

    private void addProductBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnLblMouseClicked
        // TODO add your handling code here:
        AddProduct ap = new AddProduct();
        ap.setVisible(true);
    }//GEN-LAST:event_addProductBtnLblMouseClicked

    private void returnItemsBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnItemsBtnLblMouseClicked
        // TODO add your handling code here:
        new ReturnItems().setVisible(true);
    }//GEN-LAST:event_returnItemsBtnLblMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBarcodeBtnLbl;
    private javax.swing.JLabel addDiscountBrnLbl;
    private javax.swing.JLabel addProductBtnLbl;
    private javax.swing.JLabel addProductCategoryBtnLbl;
    private javax.swing.JLabel addProductTypeBtnLbl;
    private javax.swing.JLabel addStoreLocationBtnLbl;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable qrTbl;
    private javax.swing.JLabel returnItemsBtnLbl;
    // End of variables declaration//GEN-END:variables

    private void tableDataLoader() {
        String path = "POS System QR";
        // creating a file object
        File directory = new File(path);

        // creating an object of the class DisplayFileExample
        DisplayFileExample obj = new DisplayFileExample();

        // Clear existing data in the table
        //tableDataClear();
        // Check if the directory exists
        if (directory.exists() && directory.isDirectory()) {
            // Get all PNG files in the directory
            File[] pngFiles = directory.listFiles((dir, name) -> name.toLowerCase().endsWith(".png"));

            // Check if there are any PNG files
            if (pngFiles != null && pngFiles.length > 0) {
                // Assuming you have a DefaultTableModel for your table
                DefaultTableModel model = (DefaultTableModel) qrTbl.getModel();

                // Loop through each PNG file
                for (File pngFile : pngFiles) {
                    // Assuming you want to display the file name in the second column
                    String fileName = pngFile.getName();

                    // Create an ImageIcon from the PNG file
                    ImageIcon imageIcon = new ImageIcon(pngFile.getPath());

                    // Add a row with the image and file name to the table
                    model.addRow(new Object[]{imageIcon, fileName});
                }
            }
        }
    }

    private void tableDataClear() {
        try {
            while (0 <= qrTbl.getRowCount()) {
                DefaultTableModel table = (DefaultTableModel) qrTbl.getModel();
                table.removeRow(qrTbl.getRowCount() - 1);
            }
        } catch (Exception e) {
            System.out.println("Customer Management Table Data Clear : " + e);
        }
    }

}

class ImageRenderer extends DefaultTableCellRenderer {

    private final int ICON_WIDTH = 80; // Adjust the width as needed
    private final int ICON_HEIGHT = 80; // Adjust the height as needed

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        if (value instanceof ImageIcon) {
            ImageIcon originalIcon = (ImageIcon) value;

            // Get the original image
            Image originalImage = originalIcon.getImage();

            // Resize the image
            Image scaledImage = originalImage.getScaledInstance(ICON_WIDTH, ICON_HEIGHT, Image.SCALE_SMOOTH);

            // Create a new ImageIcon from the scaled image
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            setIcon(scaledIcon);

            // Set row height and width for the image column
            table.setRowHeight(row, ICON_HEIGHT);
            TableColumnModel columnModel = table.getColumnModel();
            columnModel.getColumn(column).setWidth(ICON_WIDTH);
            columnModel.getColumn(column).setPreferredWidth(ICON_WIDTH);

            // Adjust the first column width to match the image
            columnModel.getColumn(0).setMinWidth(ICON_WIDTH);
            columnModel.getColumn(0).setMaxWidth(ICON_WIDTH);
        } else {
            setIcon(null);
        }
        return this;
    }
}
