/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.zx.shopmanagementsystem.forms;

import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;
import com.zx.shopmanagementsystem.dbconnection.JDBC;
import com.zx.shopmanagementsystem.table.TableCustom;
import com.zx.shopmanagementsystem.ui.SupplierDetails;
import com.zx.shopmanagementsystem.ui.SupplierRegistration;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SupplierManagement extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    Func func = new Func();
    IconLocation il = new IconLocation();
    JDBC DB = new JDBC();

    public SupplierManagement() {
        initComponents();
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        tableDataClear();
        tableDataLoader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSupplierBtnLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supllierTbl = new javax.swing.JTable();
        iconLbl = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1015, 738));
        setPreferredSize(new java.awt.Dimension(1116, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSupplierBtnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSupplierBtnLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addSupplierBtnLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addSupplierBtnLblMouseExited(evt);
            }
        });
        add(addSupplierBtnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 90, 210, 40));

        supllierTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Supplier Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supllierTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supllierTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supllierTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 157, 1020, 520));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\SupplierManagement.png")); // NOI18N
        add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addSupplierBtnLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSupplierBtnLblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addSupplierBtnLblMouseEntered

    private void addSupplierBtnLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSupplierBtnLblMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addSupplierBtnLblMouseExited

    private void addSupplierBtnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSupplierBtnLblMouseClicked
        // TODO add your handling code here:
        SupplierRegistration sr = new SupplierRegistration(this);
        sr.setVisible(true);
    }//GEN-LAST:event_addSupplierBtnLblMouseClicked

    private void supllierTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supllierTblMouseClicked
        // TODO add your handling code here:
        int row = supllierTbl.getSelectedRow();
        int supplierID = Integer.parseInt((String) supllierTbl.getModel().getValueAt(row, 0));
        SupplierDetails sd = new SupplierDetails(this);
        sd.setVisible(true);
        sd.dataLoad(supplierID);
    }//GEN-LAST:event_supllierTblMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addSupplierBtnLbl;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable supllierTbl;
    // End of variables declaration//GEN-END:variables
    private void tableDataLoader() {
        try {
            java.sql.ResultSet rs = DB.getdata("SELECT * FROM supplier");
            while (rs.next()) {
                String supId = String.valueOf(rs.getInt("supplier_id"));
                String supName = String.valueOf(rs.getString("supplier_name"));
                String supContact = String.valueOf(rs.getString("supplier_contact"));

                System.out.println("Supplier ID" + supId);
                System.out.println("Supplier Name" + supName);
                System.out.println("Supplier Contact" + supContact);

                String table_data[] = {supId, supName, supContact};
                DefaultTableModel table = (DefaultTableModel) supllierTbl.getModel();
                table.addRow(table_data);

            }
        } catch (Exception ex) {
            System.out.println("Supplier Management Table Data Loader : " + ex);
        }
    }

    private void tableDataClear() {
        try {
            while (0 <= supllierTbl.getRowCount()) {
                DefaultTableModel table = (DefaultTableModel) supllierTbl.getModel();
                table.removeRow(supllierTbl.getRowCount() - 1);
            }
        } catch (Exception e) {
            System.out.println("Supplier Management Table Data Clear : " + e);
        }
    }

    public void setTable() {
        tableDataClear();
        tableDataLoader();
    }
}
