/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.zx.shopmanagementsystem.forms;

import com.zx.shopmanagementsystem.assests.Func;
import com.zx.shopmanagementsystem.assests.IconLocation;

/**
 *
 * @author User
 */
public class UserManagement extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    Func func = new Func();
    IconLocation il = new IconLocation();

    public UserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserBtnIcon = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1015, 738));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addUserBtnIcon.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\icons\\AddUserPurpleIcon.png")); // NOI18N
        addUserBtnIcon.setPreferredSize(new java.awt.Dimension(214, 36));
        addUserBtnIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addUserBtnIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addUserBtnIconMouseExited(evt);
            }
        });
        add(addUserBtnIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        iconLbl.setIcon(new javax.swing.ImageIcon("C:\\ShopManagementSystem\\src\\main\\java\\com\\zx\\shopmanagementsystem\\images\\UserManagement.png")); // NOI18N
        iconLbl.setPreferredSize(new java.awt.Dimension(1015, 738));
        add(iconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addUserBtnIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserBtnIconMouseEntered
        // TODO add your handling code here:
        func.iconSetter(addUserBtnIcon, il.addUserWhiteIcon);
    }//GEN-LAST:event_addUserBtnIconMouseEntered

    private void addUserBtnIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserBtnIconMouseExited
        // TODO add your handling code here:
        func.iconSetter(addUserBtnIcon, il.addUserPurpleIcon);
    }//GEN-LAST:event_addUserBtnIconMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addUserBtnIcon;
    private javax.swing.JLabel iconLbl;
    // End of variables declaration//GEN-END:variables
}
